name: travelmate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  get: ^4.6.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SFPro
      fonts:
        - asset: fonts/SFPRODISPLAYREGULAR.otf
        - asset: fonts/SFPRODISPLAYMEDIUM.otf
          weight: 600
        - asset: fonts/SFPRODISPLAYBOLD.otf
          weight: 700
