name: travelmate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  get: ^4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts: 
    - family: SFPro
      fonts:
        - asset: fonts/SFPRODISPLAYREGULAR.otf
        - asset: fonts/SFPRODISPLAYMEDIUM.otf
          weight: 600
        - asset: fonts/SFPRODISPLAYBOLD.otf
          weight: 700
        - asset: fonts/SFPRODISPLAYTHINITALIC.otf
          weight: 200
          style: italic
        - asset: fonts/SFPRODISPLAYULTRALIGHTITALIC.otf
          weight: 300
          style: italic
        - asset: fonts/SFPRODISPLAYLIGHTITALIC.otf
          weight: 400
          style: italic
        - asset: fonts/SFPRODISPLAYHEAVYITALIC.otf
          weight: 700
          style: italic
        - asset: fonts/SFPRODISPLAYSEMIBOLDITALIC.otf
          weight: 800
          style: italic
        - asset: fonts/SFPRODISPLAYBLACKITALIC.otf
          weight: 900
          style: italic


